events {
    worker_connections 1024;
}

http {
    upstream nextjs {
        server nextjs-app:3000;
    }
    upstream nestjs {
        server nestjs-api:4000;
    }
    server {
        listen 80;
        server_name printbyfalcon.com www.printbyfalcon.com;
        location / {
            proxy_pass http://nextjs;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
    server {
        listen 80;
        server_name api.printbyfalcon.com;
        location / {
            proxy_pass http://nestjs;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
